Fatal error: exception Failure("Return outside functions")